[feat] [.NET] 01 - Back-End Criação do usuário
gregoryzimmerwarren/acceleration-everest-03-dotnet pull request #1
Opened 2022-09-13 17:19 UTC by gregoryzimmerwarren

**Requisitos:**
_Adicionar validação para impedir de adicionar/atualizar um Customer com e-mail e Cpf duplicado_
- Sempre validar que o Customer existe antes de tentarmos atualizar ou deletar. Caso não exista devemos retornar NotFound informando que não encontramos o cliente para o campo X. PS: Também deve-se informar o valor da requisição utilizado para buscar no campo X.

_Para requisições Post ou Put/Patch, todos os campos devem serem validados._
- Validação da confirmação de e-mail;

- Para o campo cpf devemos aceitar com e sem pontuação, salvar no banco sem pontuação e deve ser validado cálculo dos dígitos para verificar se o cpf é válido;
 
_Retornos dos endpoints_
 - Métodos Post(criação de usuário): deve retornar status code 201 em caso de sucesso;

- Métodos Put/Patch: deve retornar apenas status code 200;

- Método Get: deve retornar response e status code 200 em caso de sucesso.

**Critérios de Aceitação**
- Esses dados deverão ser salvo em memória através de uma lista privada dentro da classe de serviço injetada com LifeTime singleton

2022-09-14 16:27 UTC, LeonardoAlthoff commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +        CustomerValidator _validator = new();
Realizar a validação automática através do Program.

2022-09-14 16:29 UTC, LeonardoAlthoff commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +        }
Adicionar verificação de nulo.

2022-09-14 16:31 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +        }
Retornar booleano ou ArgumentNullException com try catch na controller.

2022-09-14 16:33 UTC, LeonardoAlthoff commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +        }
Alocar o resultado em var para melhor debugar.

2022-09-14 16:34 UTC, LeonardoAlthoff commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +                return NotFound();
Necessário retornar a informação de qual o campo não encontrou resultado.
```suggestion
                return NotFound($"Did not found customer for Id: {id}");
```

2022-09-14 16:35 UTC, LeonardoAlthoff commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +                return NotFound();
Mesmo caso acima.

2022-09-14 16:38 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Data.csproj
> +
Necessário excluir os pacotes não utilizados.

2022-09-14 16:39 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Data.csproj
> +
Excluir pacotes não utilizados. 
```suggestion

```

2022-09-14 17:13 UTC, LeonardoAlthoff requested changes
Revisar comentários.

2022-09-14 17:13 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +        }
Retornar o método diretamente, eis que o retorno será nulo ou o customer requerido.
```suggestion
        {
            var entity = _customersList.FirstOrDefault(customer => customer.Id == id);

            return entity;
        }
```

2022-09-14 17:13 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +    }
É interessante utilizar a função FindIndex() pois ele te dará a única variável necessária para o update.

2022-09-14 17:13 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Validators/CustomerValidator.cs
> +                .WithMessage("Cpf must be valid.");
A validação do Length do CPF se torna desnecessária com a formatação diretamente no construtor.

2022-09-14 17:13 UTC, LeonardoAlthoff commented on ApiCustomer/Data/Data/Validators/CustomerValidator.cs
> +            cpf = cpf.Replace(".", "").Replace("-", "");
Igual caso acima.

2022-09-14 19:59 UTC, viniciusoliveira-warren commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +            }
```suggestion
            var emailExists = _customersList.Any(customer => customer.Email == customerToCreate.Email);
            if (emailExists)
            {
                throw new ArgumentException("Email is already registered");
            }
            
            var cpfExists = _customersList.Any(customer => customer.Cpf == customerToCreate.Cpf);
            if (cpfExists)
            {
                throw new ArgumentException("Cpf is already registered");
            }
```

2022-09-14 20:02 UTC, viniciusoliveira-warren commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +            var emailExists = _customersList.Any(customer => customer.Email == entityToUpdate.Email);
Validar também que o Id é diferente do entityToUpdate porque do contrário você vai encontrar a própria entidade que está buscando para fazer update

2022-09-14 20:12 UTC, AlanmWarren commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +            customerToCreate.Id = _customersList.Count + 1;
Sua lógica de auto incrementar IDs está meio quebrada

Exemplo:
Lista com os IDs: 1, 2, 3, 4; count = 4,
Adicionar novo customer: next id = count + 1 = 5
Resultado = 1, 2, 3, 4, 5
Até aí tudo bem, irá adicionar um novo ID sem problemas

Se eu deletar um customer e depois adicionar um novo, ficará assim: (Customer deletado: id = 1)
Lista com os IDs: 2, 3, 4, 5; count = 4;
Adicionar novo customer: next id = count + 1 = 5
Resultado = 2, 3, 4, 5, 5
O ID = 5 se repete

Se eu deletar novamente um customer e depois adicionar um novo... (Customer deletado: id = 2)
Lista com os IDs: 3, 4, 5, 5; count = 4;
Adicionar novo customer: next id = count + 1 = 5
Resultado = 3, 4, 5, 5, 5
O ID = 5 se repete

Resultado Final => IDs: 3, 4, 5, 5, 5; count = 5
Não podemos repetir ID, pois é um identificador individual.

2022-09-15 16:55 UTC, viniciusoliveira-warren commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +            if (result == false)
```suggestion
            if (!result)
```

2022-09-15 16:55 UTC, viniciusoliveira-warren commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
> +                if (result == false)
```suggestion
                if (!result)
```

2022-09-15 16:58 UTC, viniciusoliveira-warren commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +            }
Replicar estrutura da validação no método Create

2022-09-15 16:59 UTC, viniciusoliveira-warren commented on ApiCustomer/Data/Data/Repositories/CustomerRepository.cs
> +            customerToUpdate.Id = _customersList[index].Id;
```suggestion
            var index = _customersList.FindIndex(customer => customer.Id == customerToUpdate.Id);
            if(index == -1) return false;

            customerToUpdate.Id = _customersList[index].Id;
```

2022-09-15 17:09 UTC, viniciusoliveira-warren approved these changes

2022-09-15 17:09 UTC, merged