feat : Project adapted for Onion Architecture
gregoryzimmerwarren/acceleration-everest-03-dotnet pull request #2
Opened 2022-09-15 18:17 UTC by gregoryzimmerwarren

2022-09-15 19:08 UTC, LucasPerinWarren requested changes

2022-09-15 20:13 UTC, viniciusoliveira-warren approved these changes

2022-09-16 11:20 UTC, merged

2022-09-16 12:30 UTC, AlanmWarren commented on ApiCustomer/Data/DomainService/Services/ICustomerService.cs
> +    public interface ICustomerService
Recomendo colocar as interfaces em uma pasta com nome Interfaces

2022-09-16 12:32 UTC, AlanmWarren commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
>                  return NotFound($"Did not found customer for Id: {id}");
Recomendo o uso de `if` ternário

2022-09-16 12:33 UTC, AlanmWarren commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
>                  return NotFound($"Did not found customer for Id: {id}");
Recomendo o uso de if ternário

2022-09-16 12:33 UTC, AlanmWarren commented on ApiCustomer/Data/CostumerApi/Controllers/CustomerController.cs
>                  return Created("", customer.Id);
Recomendo o uso de if ternário