[.NET] 03 - Boas práticas na construção de API
gregoryzimmerwarren/acceleration-everest-03-dotnet pull request #4
Opened 2022-09-19 12:09 UTC by gregoryzimmerwarren

**Documentação técnica do desafio**
- Será utilizado a biblioteca AutoMapper para mapeamento de entidades.

- Profiles de mapeamento das entidades definidos na camada de aplicação.

**Critérios para aceitação**
- Requests recebidas pelos endpoints da api devem ser mapeadas para entidades de domínio; Ex: GetCustomerByDocumentRequest

- Antes das AppServices retornarem os dados para api devemos mapear a(s) entidade(s) de domínio para entidade(s) de response da api; Ex: CustomerResult

- Todos os mapeamentos de entidade(s) devem serem feitas na camada de aplicação(Application)

2022-09-19 12:19 UTC, LeonardoAlthoff commented on ApiCustomer/AppServices/AppServices.csproj
> +  </ItemGroup>
Falta a referência do FluentValidation

2022-09-19 12:28 UTC, LeonardoAlthoff commented on ApiCustomer/CostumerApi/Controllers/CustomerController.cs
>          {
É preciso trocar o parâmetro que você está passando. Ele precisa ser igual à função chamada.

2022-09-19 12:31 UTC, LeonardoAlthoff commented on ApiCustomer/CostumerApi/Controllers/CustomerController.cs
>          {
Igual o de cima, passar o DTO criado neste card

2022-09-19 12:33 UTC, LeonardoAlthoff commented on ApiCustomer/CostumerApi/CustomerApi.csproj
>      <ProjectReference Include="..\AppServices\AppServices.csproj" />
A camada da API deve ter como referência apenas os serviços da camada de aplicação
```suggestion
  <ItemGroup>
    <ProjectReference Include="..\AppServices\AppServices.csproj" />
```

2022-09-19 12:37 UTC, LeonardoAlthoff commented on ApiCustomer/DomainService/Services/CustomerService.cs
>              if (emailExists)
Como foi enviado o CustomerModel com as informações apenas do DTO, ele não possui nenhum Id. É necessário fazer a lógica e atribuí-lo aqui

2022-09-19 12:44 UTC, LeonardoAlthoff commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +        public bool Update(CustomerModel customerToUpdate)
Como no anterior, necessário passar o DTO, não o model da camada de domínio.

2022-09-19 16:21 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/DTOs/GetCustomerDto.cs
> +    public class GetCustomerDto
Para o que serve esse dto?

2022-09-19 16:24 UTC, gregoryzimmerwarren commented on ApiCustomer/AppModels/DTOs/GetCustomerDto.cs
> +    public class GetCustomerDto
Esse é o Dto que vai ser utilizado nos métodos GetAll e GetById. Ele vai ser o responsável por receber os dados que estão no banco e que posteriormente vão ser apresentados ao usuário como resposta dos métodos do tipo Get.

2022-09-19 18:19 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/DTOs/GetCustomerDto.cs
> +    public class GetCustomerDto
Então tem que mudar o nome, porque atualmente não está condizendo com o que está fazendo de fato

2022-09-19 18:19 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/DTOs/PostCustomerDto.cs
> +        public PostCustomerDto(
Do que se trata essa entidade? não seria para criar aqui?

2022-09-19 18:19 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/DTOs/PutCustomerDto.cs
> +        public PutCustomerDto(
Do que se trata essa entidade? não seria para atualizar aqui?

2022-09-19 18:20 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Services/CustomerAppService.cs
```suggestion
        private readonly ICustomerService _customerService;
```

2022-09-19 18:20 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Services/CustomerAppService.cs
> +            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
```suggestion
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
```

2022-09-19 18:23 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Services/CustomerAppService.cs
> +            return _mapper.Map<List<GetCustomerDto>>(customers);
Se quem está chamando esse método pode manipular (adicionar/remover) os itens da coleção, então o retorno pode ser um IList.

Se quem está chamando deve apenas iterar em cima ou usar funcionalidades básicas, então na perspectiva de design sempre é preferível usar o tipo menos derivado possível (IEnumerable ou ICollection).

2022-09-19 18:24 UTC, viniciusoliveira-warren requested changes
Renomear pasta ApiCustomer => src

2022-09-19 18:26 UTC, viniciusoliveira-warren requested changes
Não precisa pasta /dtos dentro de AppModels, esse projeto é exclusivamente para isso o que torna redundante

2022-09-19 18:27 UTC, viniciusoliveira-warren reviewed
Não é uma Api apenas para customer, renome Pasta de CustomerApi para algo como /Api

2022-09-19 18:28 UTC, viniciusoliveira-warren commented on ApiCustomer/DomainModels/Models/CustomerModel.cs
> +    public class CustomerModel : BaseModel
1. Redundante ter model como sufixo na entidade porque já estamos na camada de DomainModels
2. Não precisa criar pasta /models. Mesmo caso da AppModels

2022-09-19 18:31 UTC, viniciusoliveira-warren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +        public List<CustomerModel> GetAll()
[Mesmo comentário](https://github.com/gregoryzimmerwarren/acceleration-everest-03-dotnet/pull/4#discussion_r974548786)

2022-09-19 18:59 UTC, gregoryzimmerwarren commented on ApiCustomer/AppModels/DTOs/GetCustomerDto.cs
> +    public class GetCustomerDto
Coloquei como ResultCustomerDto, pode ser ?

2022-09-19 18:59 UTC, gregoryzimmerwarren commented on ApiCustomer/AppModels/DTOs/PostCustomerDto.cs
> +        public PostCustomerDto(
Coloquei como CreateCustomerDto, pode ser ?

2022-09-19 18:59 UTC, gregoryzimmerwarren commented on ApiCustomer/AppModels/DTOs/PutCustomerDto.cs
> +        public PutCustomerDto(
Coloquei como UpdateCustomerDto, pode ser ?

2022-09-19 19:29 UTC, gregoryzimmerwarren commented on ApiCustomer/AppServices/Services/CustomerAppService.cs
> +            return _mapper.Map<List<GetCustomerDto>>(customers);
Certo, alterado para IEnumerable não será usada para manipulações

2022-09-19 19:29 UTC, gregoryzimmerwarren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +        public List<CustomerModel> GetAll()
Certo, alterado para IEnumerable não será usada para manipulações

2022-09-20 14:25 UTC, gregoryzimmerwarren commented on ApiCustomer/DomainModels/Extensions/StringExtensions.cs
> +﻿namespace DomainModels.Extensions
Alterado

2022-09-20 14:40 UTC, gregoryzimmerwarren commented on ApiCustomer/AppServices/AppServices.csproj
> +    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
Alterado

2022-09-20 16:12 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Validators/PutCustomerDtoValidator.cs
> +                .Equal(costumer => costumer.EmailConfirmation);
Por que?

2022-09-20 16:13 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/ResultCustomerDto.cs
> +    }
```suggestion
    protected ResultCustomerDto() {}
```

2022-09-20 16:13 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/ResultCustomerDto.cs
> +}
```suggestion
    public string PostalCode { get; set; }
}
```

2022-09-20 16:15 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Extensions/DateTimeExtensions.cs
> +        return false;
Essa lógica não funciona, se quiser entregar esse "extra" tem que corrigir a lógica
```suggestion
        return DateTime.Now.Year - dataNascimento.Year >= 18;
```

2022-09-20 16:22 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Extensions/StringExtensions.cs
> +    public static bool BeValidCpf(this string cpf)
Isso não deveria ser um método de StringExtensions pois sempre será usado apenas no FluentValidation. Temos 2 alternativa para resolver isso.

1. Método privado duplicado no validator de criação e alteração do customer
2. Criar uma classe de ValidatorCommon, colocar esse método nessa classe e utiliza-lo nos 2 validators

PS: Renomear método para IsValidCpf

2022-09-20 16:22 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Extensions/StringExtensions.cs
> +    public static string CpfFormatter(this string cpf)
```suggestion
    public static string FormatCpf(this string cpf)
```

2022-09-20 16:23 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Profiles/CustomerProfiles.cs
> +public class CustomerProfiles : Profile
```suggestion
public class CustomerProfile : Profile
```

2022-09-20 16:23 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Validators/PostCustomerDtoValidator.cs
> +public class PostCustomerDtoValidator : AbstractValidator<CreateCustomerDto>
Renomear classe de acordo com a entidade validada

2022-09-20 16:23 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Validators/PutCustomerDtoValidator.cs
> +public class PutCustomerDtoValidator : AbstractValidator<UpdateCustomerDto>
Renomear classe de acordo com a entidade validada

2022-09-20 16:24 UTC, viniciusoliveira-warren commented on ApiCustomer/AppServices/Validators/PutCustomerDtoValidator.cs
> +            .WithMessage("Customer must be over 18 years old.");
```suggestion
            .Must(customer => customer.IsOver18())
            .WithMessage("Customer must be over 18 years old.");
```

2022-09-20 16:25 UTC, viniciusoliveira-warren commented on ApiCustomer/DomainModels/Customer.cs
> +    public string EmailConfirmation { get; set; }
Não faz sentido ter esse campo no banco

2022-09-20 16:26 UTC, viniciusoliveira-warren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +            throw new ArgumentException("Email is already registered");
Qual e-mail?

2022-09-20 16:27 UTC, viniciusoliveira-warren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +        var emailExists = _customersList.Any(customer => customer.Email == customerToCheck.Email);
```suggestion
        return _customersList.Any(customer => customer.Email == customerToCheck.Email);
```

2022-09-20 16:27 UTC, viniciusoliveira-warren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +        var cpfExists = _customersList.Any(customer => customer.Cpf == customerToCheck.Cpf);
```suggestion
        return _customersList.Any(customer => customer.Cpf == customerToCheck.Cpf);
```

2022-09-20 17:08 UTC, gregoryzimmerwarren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +            throw new ArgumentException("Email is already registered");
Alterado

2022-09-20 17:08 UTC, gregoryzimmerwarren commented on ApiCustomer/DomainService/Services/CustomerService.cs
> +            throw new ArgumentException("Cpf is already registered");
Alterado

2022-09-20 17:10 UTC, gregoryzimmerwarren commented on ApiCustomer/AppServices/Extensions/StringExtensions.cs
> +    public static bool BeValidCpf(this string cpf)
Alterado

2022-09-20 17:13 UTC, gregoryzimmerwarren commented on ApiCustomer/DomainModels/Customer.cs
> +    public string EmailConfirmation { get; set; }
Retirado

2022-09-20 17:13 UTC, gregoryzimmerwarren commented on ApiCustomer/AppModels/DTOs/GetCustomerDto.cs
> +    public class GetCustomerDto
Alterado

2022-09-21 16:48 UTC, viniciusoliveira-warren commented on ApiCustomer/AppModels/ResultCustomerDto.cs
> +public class ResultCustomerDto
```suggestion
public class CustomerResult
```

2022-09-21 16:59 UTC, viniciusoliveira-warren approved these changes

2022-09-21 17:01 UTC, merged