[.NET] 07 - Relacionamento entre tabelas
gregoryzimmerwarren/acceleration-everest-03-dotnet pull request #8
Opened 2022-10-12 16:56 UTC by gregoryzimmerwarren

**Regras de negócio**

_Deposito de dinheiro_

- Todos os depósitos de dinheiro devem ocorrer na conta corrente do usuário.

- Para depositar dinheiro em uma carteira é necessário primeiro depositar na conta corrente e depois da conta corrente transferir para a carteira.

_Resgate de dinheiro_

- Para resgatar dinheiro de uma carteira, o mesmo deve ser transferido para conta corrente.

_Resgate de produto_

- Será necessário criar uma Ordem de resgate e o produto apenas poderá ser resgatado da carteira e o dinheiro debitado na carteira quando a data de liquidação da Ordem for igual ou menor do que hoje.

_Investimento/Investir em um produto_

- Será necessário criar uma Ordem de investimento com X produto e apenas quando a data de liquidação da Ordem for igual ou menor do que hoje o produto poderá ter vinculo com a carteira e o saldo da carteira ser investido de fato.

_Quando posso deletar uma carteira_

- Quando todos produtos forem resgatados e o saldo transferido para conta corrente.

2022-10-17 11:54 UTC, LeonardoAlthoff requested changes
Revisar comentários.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        var orderMapeada = _mapper.Map<Order>(createOrderDto);
Pq em português?

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        }
Igual ao comentário anterior. Quando se busca incluir uma entidade dentro de outra, deve-se utilizar o .Include(), fornecido pelo EFCore, na camada de domínio. Assim, a responsabilidade encontra-se na camada correta, utilizamos a ferramenta proporcionada pela biblioteca e é preciso apenas uma requisição ao banco de dados.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +    }
Todos estes métodos se encaixam no comentário anterior.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        portfolioMapeado.TotalBalance = 0;
É possível fazer essa atribuição de valor diretamente no construtor da classe Portfolio. Como nenhum será criado já com saldo, faz mais sentido que seja uma regra da própria entidade.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        var portfolioMapeado = _mapper.Map<Portfolio>(createPortfolioDto);
Novamente, está em português.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        }
Se estamos dentro dos serviços da portfolio, o depósito será referente a ele, não ao bankInfo.  O depósito e saque da bankInfo devem ser reponsabilidade dos serviços daquela entidade. Até porque a conta remunerada é um produto à parte e, seguindo essa lógica, o cliente só teria acesso a ela se criasse uma carteira.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        }
Toda essa lógica é atribuição do .Include() do EFCore e pertence à camada de domínio. O mesmo vale para os demais métodos que fazem função similar.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +
A ordem não ser executada no momento em que é criada não se trata de um erro ou exceção, mas faz parte da regra de negócio. Não faz sentido tratar isso como exceção e, ao fazê-lo, você também deixa de percorrer o restante da função, o que, na prática, faz com que o investimento só seja possível nos casos em que a data for anterior.

2022-10-17 11:54 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +            throw new ArgumentException($"The amount {amount} was not credited to the portfolio Id {createOrderDto.PortfolioId}. The order liquidate in a date greater than today");
Igual comentário anterior.

2022-10-17 13:07 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioProductController.cs
> +public class PortfolioProductController : ControllerBase
Sim, concordo contigo. Deixei apenas para poder facilitar na hora de fazer as verificações. Mas já vou excluir.

2022-10-17 13:12 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/ProductController.cs
> +            return Created("", id);
Desculpe, tu diz no método Create de cada controller? Porque a única controller sem o "Id" é a CustomerBankInfo.

2022-10-17 13:15 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/Api/Controllers/ProductController.cs
> +            return Created("", id);
Na CustomerController está:
 "return Created("Id:", id);"
 No restante, está:
"return Created("", id);"

2022-10-17 13:17 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/AppModels.csproj
> +    <ProjectReference Include="..\DomainModels\DomainModels.csproj" />
Alterei para que ela passe a ver a DomainServices

2022-10-17 13:22 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Customers/CustomerResultDto.cs
> +    protected CustomerResultDto() { }
Feito

2022-10-17 13:22 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/CustomersBankInfo/CustomerBankInfoResultDto.cs
> +    public CustomerBankInfoResultDto() { }
Feito

2022-10-17 13:23 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/CustomersBankInfo/CustomerBankInfoResultForCustomerDtos.cs
> +public CustomerBankInfoResultForOthersDtos() { }
Feito

2022-10-17 13:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/ProductController.cs
> +            return Created("", id);
Ata, realmente não tinha visto isso. É que quando tu falou de string vazia, eu lembrei que como resposta vaio Id criado, dai não me fez sentido, porque não estava tendo resposta vazia. Agora faz sentido o string vazia, haha, Obrigado, já mudei.

2022-10-17 13:39 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Orders/OrderResultDto.cs
> +        Portfolio = portfolio;
Alterado

2022-10-17 13:39 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Portfolios/PortfolioResultDto.cs
> +    public PortfolioResultDto() { }
Feito

2022-10-17 13:39 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/PortfoliosProducts/PortfolioProductResultDto.cs
> +    public PortfolioProductResultDto() { }
Feito

2022-10-17 13:39 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Products/ProductResultDto.cs
> +        Type = GetEnumName(type);
Alterado

2022-10-17 13:39 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Products/ProductResultForOthersDtos.cs
> +        Type = GetEnumName(type);
Alterado

2022-10-17 13:44 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Portfolios/PortfolioResultDto.cs
> +    public List<OrderResultOtherDtos> Orders { get; set; }
Alterado

2022-10-17 13:49 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/CustomerAppService.cs
>          var customerMapeado = _mapper.Map<Customer>(createCustomerDto);
Corrigido

2022-10-17 13:50 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        var orderMapeada = _mapper.Map<Order>(createOrderDto);
Corrigido

2022-10-17 13:50 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        var portfolioMapeado = _mapper.Map<Portfolio>(createPortfolioDto);
Corrigido

2022-10-17 14:13 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        }
Eu fiz dessa forma, porque pelo diagrama que consta no card, eu entendi que o cliente poderia fazer o depósito na carteira ou na conta corrente.
E as regras de negócio diziam que todos os depósitos de dinheiro devem ocorrer na conta corrente do usuário. E que para depositar dinheiro em uma carteira é necessário primeiro depositar na conta corrente e depois da conta corrente transferir para a carteira.

No CustomerBankInfoService tem o método de depósito que faz o depósito direto lá.
Porém, o cliente só faz o depósito direto na carteira se o valor que ele quer depositar está na conta corrente, ou seja se o saldo lá for maior ou igual ao que ele quer depositar. Se não obrigatoriamente tem que ir pra conta corrente, porque todo depósito tem que ir para lá antes de ser transferido.

2022-10-18 15:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        }
Alterado para assíncrono e corrigido as requisições com o .Include().

2022-10-18 15:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +    }
Alterado para assíncrono e corrigido as requisições com o .Include().

2022-10-18 15:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        }
Alterado para assíncrono e corrigido as requisições com o .Include().

2022-10-18 15:30 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        }
Corrigido após conversa com Leonardo.

2022-10-20 17:09 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +
Alterado para utilizar o HostedService Cronos

2022-10-20 17:09 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +            throw new ArgumentException($"The amount {amount} was not credited to the portfolio Id {createOrderDto.PortfolioId}. The order liquidate in a date greater than today");
Alterado para utilizar o HostedService Cronos

2022-10-21 19:16 UTC, LucasPerinWarren reviewed
Verificar Comentários.

2022-10-21 19:16 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +    }
Por que você deletaria uma bankInfo? Se todo customer tem uma bankInfo criada automaticamente quando faz o cadastro, o correto é que não possa haver customers sem bankInfo.
```suggestion
   
```

2022-10-21 19:16 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/Infrastructure.Data/Mappings/OrderMapping.cs
> +
```suggestion
        builder.HasKey(order => order.Id)
             .ValueGenereateOnAdd();

```

2022-10-21 19:16 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/Infrastructure.Data/Mappings/PortfolioMapping.cs
> +
```suggestion
        builder.HasKey(portfolio => portfolio.Id)
             .ValueGenereateOnAdd();

```

2022-10-21 19:16 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/Infrastructure.Data/Mappings/ProductMapping.cs
> +
```suggestion
        builder.HasKey(product => product.Id)
             .ValueGenereateOnAdd();

```

2022-10-21 19:39 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Interfaces/ICustomerBankInfoService.cs
> +    Task<IEnumerable<CustomerBankInfo>> GetAllCustomersBankInfoAsync();
É vantajoso o Get ser assíncrono pois em certos fluxos podemos deixar a query rolando em outra thread enquanto fazemos X e não precisamos esperar terminar para só então usar os dados

2022-10-21 19:40 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Interfaces/ICustomerBankInfoService.cs
> +    Task<IEnumerable<CustomerBankInfo>> GetAllCustomersBankInfoAsync();
Outro detalhe que como é async podemos utilizar o CancellationToken o que é um ganho de performace caso necessário cancelar a requisição

2022-10-21 19:41 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Interfaces/ICustomerBankInfoService.cs
> +    Task<IEnumerable<CustomerBankInfo>> GetAllCustomersBankInfoAsync();
Eu manteria assíncrono, aqui tem um [link](https://stackify.com/when-to-use-asynchronous-programming/) com mais motivos

2022-10-21 20:32 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainService/Interfaces/ICustomerBankInfoService.cs
> +    Task<IEnumerable<CustomerBankInfo>> GetAllCustomersBankInfoAsync();
Massa, obrigado pelo esclarecimento Vini, concordo super contigo.

2022-10-24 11:57 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/AppModels.csproj
> +    <ProjectReference Include="..\DomainService\DomainServices.csproj" />
Corrigido

2022-10-24 12:03 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Portfolios/CreatePortfolio.cs
> +    public decimal AccountBalance { get; set; }
Retirados

2022-10-24 12:22 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/PortfoliosProducts/CreatePortfolioProduct.cs
> +{
Eu utilizo no meu PortfolioAppService. Quando executa a ordem de compra, é feito um get passando ProductId e PortfolioId, se não encontrar nada ele cria uma entidade PortfolioProduct

2022-10-24 12:28 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/CustomersBankInfo/CustomerBankInfoResultForCustomerDtos.cs
> +{
Porque eu defini saídas diferentes para todas as entidades, menos PortfolioProduct.

Por exemplo nesse caso do BankInfo, nos meu GET de Customer, eu vou ter as informações do meu BankInfo, mas uma das informações dele é justamente o Customer que ele está vinculado. Então para não ficar apresentando o mesmo dado, quando o BankInfo vem de um GET dele ele apresenta a informação de Customer, mas se ele vem por um GET de Customer não apresenta.

2022-10-24 12:32 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/CustomerBankInfoAppService.cs
> +        return _mapper.Map<CustomerBankInfoResult>(customerBankInfo);
Retirado

2022-10-24 12:38 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/CustomerAppService.cs
> +    public async Task<IEnumerable<CustomerResult>> GetAllCustomersAsync()
Mantido conforme comentário do Vini

2022-10-24 12:38 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +    {
Mantido conforme comentário do Vini

2022-10-24 12:49 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        var unitPrice = produt.UnitPrice;
Criei o novo método, e já alterei o OrderAppService

2022-10-24 13:31 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +    }
Da mesma forma que não pode haver Customer sem BankInfo, penso que o contrário também é verdadeiro, não? Como eu tenho um método para deletar o Customer, quando chamo ele também chamo o do BankInfo para deletar o BankInfo.

2022-10-24 13:33 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Validators/Update/UpdateOrderDtoValidator.cs
> +    {
Revisados

2022-10-24 13:39 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainModels/Models/Product.cs
> +    public List<PortfolioProduct> PortfolioProducts { get; set; }
Porque products tem relacionamento com eles:
Products N:N Portfolio
Product 1:N Order

E pela documentação entendi que deveria estar desta forma

2022-10-24 13:52 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioProductAppService.cs
> +    }
Excluído e alterado na PortfolioAppService para chamar direto sua service.

2022-10-24 13:56 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        mappedOrder.NetValue = mappedOrder.Quotes * unitPrice;
Na Order nós não temos o UnitPrice, apenas no Product.

Você acha necessário criar esse parâmetro na Order, mesmo podendo utilizar a do Product?

2022-10-24 14:01 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +    }
Por que seria perigoso?

Quando pensei nesse GetAll imaginei que talvez fosse interessante para sabermos quantas carteiras teríamos no sistema.
Mas posso sim excluir o método.

2022-10-24 14:07 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        return totalQuotes;
Sim, já criei o método lá. Obrigado.

2022-10-24 14:30 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppModels/PortfoliosProducts/CreatePortfolioProduct.cs
> +{
Você está fazendo isso direto com a entidade da domain, através do método da camada de serviço, teu createPortfolioProduct não está sendo utilizado ali.

2022-10-24 14:37 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        mappedOrder.NetValue = mappedOrder.Quotes * unitPrice;
No card a solicitação é que NetValue seja uma multiplicação de quotes * unitPrice, isso se torna uma regra de negócio. Então acho interessante ter a indicação do valor unitário do produto na order.

2022-10-24 14:47 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/AppModels/CustomersBankInfo/CustomerBankInfoResultForCustomerDtos.cs
> +{
É isso ai mesmo @gregoryzimmerwarren, devemos fazer esse desacoplamento de contratos com a api para diferentes rotas. Minha sugestão para ti seria refatorar os nomes desses contratos porque neste momento não está ideal apesar do nome estar condizente

2022-10-24 14:50 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainModels/Models/Product.cs
> +    public List<PortfolioProduct> PortfolioProducts { get; set; }
Os relacionamentos nesse caso apenas nos dizem que vários produtos podem estar em vários portfólios e apenas 1 produto por ordem. Porém produtos não têm porque conhecer as ordens que estão alocados e nem os portfólios.

2022-10-24 14:52 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +    }
Você tem razão, não me atentei ao fato que ele estava sendo utilizado juntamente com customer. Desculpe.

2022-10-24 14:54 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/AppModels/CustomersBankInfo/CustomerBankInfoResultForCustomerDtos.cs
> +{
Estou pensando em uma nomenclatura...

2022-10-24 14:56 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/PortfoliosProducts/CreatePortfolioProduct.cs
> +{
Sim, não havia percebido que realizando outra sugestão sua acabei não utilizando mais. Obrigado.

2022-10-24 14:56 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +    }
Mas aqui estamos invertendo a ordem, Conta corrente depende de do Cliente e não o contrário

2022-10-24 14:58 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +    }
Apontei por conter informações de todas as operações de todas carteiras e não ter um filtro, ao meu ver torna o endpoint perigoso pela livre apresentação de dados, porém posso estar equivocado. Recomendo manter o método mesmo.

2022-10-24 14:59 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +    }
Quando deletamos Conta corrente esperando que delete o cliente junto estamos cometendo um grande erro, o fluxo correto seria deletar o Cliente e como cliente e conta corrente é 1:1, a conta corrente seria deletada junto

2022-10-24 14:59 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/CustomersBankInfo/CustomerBankInfoResultForCustomerDtos.cs
> +{
Obrigado @viniciusoliveira-warren estou pensando também, mas até o momento não tive nenhuma ideia.

2022-10-24 15:01 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +    }
Entendi seu ponto, realmente fiquei na dúvida agora.

@viniciusoliveira-warren poderias dizer o que seria melhor fazer? Obrigado.

2022-10-24 15:04 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +    }
Único cenário que podemos fazer GetAll sem filtros é quando a tabela é fixa e possui muito poucos dados (Entorno dos 200)

2022-10-24 15:05 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +    }
E em uma tabela como de carteiras onde o crescimento é exponencial, pode ter certeza que em um cenário real é apenas questão de tempo até esse GetAll derrubar todo o sistema

2022-10-24 15:14 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +    }
Sim, mas é isso que está acontecendo.
Quando o Cliente é deletado a conta corrente também é. Mas o inverso não, até porque minha controller da conta corrente não permite a exclusão apenas dela.

2022-10-24 15:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        mappedOrder.NetValue = mappedOrder.Quotes * unitPrice;
Certo, mas dai minha nova dúvida é, a necessidade desse UnitPrice na order seria apenas por questão de visualização? Porque como product e order tem relacionamento, nos meus GETs de order o UnitPrice do product sempre aparece.

2022-10-24 15:35 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainModels/Models/Product.cs
> +    public List<PortfolioProduct> PortfolioProducts { get; set; }
Mas então Customer também não pode conhecer os porftolios atrelados a ele, e um portfolio também não pode conhecer as orders atreladas a ele?

2022-10-24 16:01 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainModels/Models/Product.cs
> +    public List<PortfolioProduct> PortfolioProducts { get; set; }
A entidade customer não tem portfolios... Já o portfolio precisa sim conhecer as ordens. Podemos pensar da seguinte forma... Um customer não precisa necessariamente de portfolios para existir ( pode ter somente a bankinfo)... Quando portfolios existem, eles são relacionados aos customers pelo id e só recebem produtos através de uma ordem, portanto portfolios sabem os produtos e as ordens que estão nele. Produtos, portanto aparecem seguindo a ideia de customer, não precisam necessariamente saber onde estão alocados quando falamos de entidades. E sabemos onde um produto está alocado através da tabela intermediária.

2022-10-24 16:06 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppServices/Services/OrderAppService.cs
> +        mappedOrder.NetValue = mappedOrder.Quotes * unitPrice;
É necessário pela regra de negócio, pois netvalue precisa chegar aos requests e results com a multiplicação feita. Como você multiplicaria ordens com produtos no construtor?

2022-10-27 18:07 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/Api/Controllers/CustomerBankInfoController.cs
> +    [HttpPatch("depositInCustomerBankInfo/{customerId}")]
```suggestion
    [HttpPatch("deposit/{customerId}")]
```

2022-10-27 18:08 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/Api/Controllers/CustomerBankInfoController.cs
> +            var total = await _customerBankInfoAppService.GetTotalByCustomerIdAsync(customerId).ConfigureAwait(false);
O que seria esse total?

2022-10-27 18:13 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/CustomerBankInfoController.cs
> +            var total = await _customerBankInfoAppService.GetTotalByCustomerIdAsync(customerId).ConfigureAwait(false);
O AccountBalance

2022-10-27 18:17 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/Infrastructure.Data/DependencyInjections/InfrastructureDataExtensions.cs
> +    public static class InfrastructureDataExtensions
O nome é de acordo com o tipo que você está estendendo 
```suggestion
    public static class IServiceCollectionExtensions
```

2022-10-27 18:21 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Infrastructure.Data/DependencyInjections/InfrastructureDataExtensions.cs
> +    public static class InfrastructureDataExtensions
Certo. Mudo todos então né?

2022-10-27 18:54 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/Infrastructure.Data/DependencyInjections/InfrastructureDataExtensions.cs
> +        public static IServiceCollection AddInfrastructureDataDependecyInjections(this IServiceCollection services, IConfiguration configuration)
Padrão microsoft
```suggestion
        public static IServiceCollection AddInfrastructureDataConfiguration(this IServiceCollection services, IConfiguration configuration)
```

2022-10-27 19:15 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Services/CronJobExecuteOrders.cs
> +");
Exemplo de como mensurar tempo levado para ação
![image](https://user-images.githubusercontent.com/96585621/198378735-18371b16-322e-4b99-967e-73d49c557303.png)

2022-10-27 19:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Services/CronJobExecuteOrders.cs
> +");
Obrigado. Vou alterar.

2022-10-27 22:26 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Services/CronJobExecuteOrders.cs
> +");
```suggestion
            _logger.LogError(exception, "Error occurred in CronJobExecuteOrders.");
```

2022-10-27 22:27 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Services/CronJobExecuteOrders.cs
> +");
[Porque não devemos fazer interpolação de string ao loggar mensagens](https://youtu.be/6zoMd_FwSwQ)

2022-10-27 22:31 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Services/CronJobExecuteOrders.cs
> +");
```suggestion
            var stopWatch = StopWatch.StartNew();
            _logger.LogInformation("CronJobExecuteOrders started.");

            var scope = _serviceScopeFactory.CreateScope();
            var repository = scope.ServiceProvider.GetRequiredService<IPortfolioAppService>();
            await repository.ExecuteOrdersOfTheDayAsync().ConfigureAwait(false);

            _logger.LogInformation("CronJobExecuteOrders finished processing. Time taken: {elapsedMilliseconds}", stopWatch.ElapsedMilliseconds);
            stopWatch.Stop();
```

2022-10-27 22:32 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Program.cs
> +    .Build();
```suggestion
        services.AddInfrastructureDataDependecyInjections(hostContext.Configuration);
        services.AddAutoMapper(Assembly.Load(nameof(AppServices)));
    })
    .Build();
```

2022-10-27 22:40 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/DependecyInjection/HostedServiceCronosExtensions.cs
> +            throw new ArgumentNullException(nameof(ScheduleConfig<T>.CronExpression), @"Empty Cron Expression is not allowed.");
```suggestion
            throw new ArgumentNullException(nameof(config.CronExpression));
```

2022-10-27 22:41 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/HostedServiceCronos/DependecyInjection/HostedServiceCronosExtensions.cs
> +            throw new ArgumentNullException(nameof(options), @"Please provide Schedule Configurations.");
```suggestion
            throw new ArgumentNullException(nameof(options));
```

2022-10-27 22:43 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +        if (products.Count == 0)
```suggestion
        if (!products.Any())
```

2022-10-27 22:45 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +            throw new ArgumentNullException($"No product found");
Aqui estamos fazendo um GetAll sem filtro algum, não faz sentido estourar exceção de NotFound porque apenas não tem dados mesmo

2022-10-27 22:52 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +            throw new ArgumentNullException($"No product found for Id: {id}");
```suggestion
        var product = await repository.SingleOrDefaultAsync(query).ConfigureAwait(false)
            ?? throw new ArgumentNullException($"No product found for Id: {id}");
```

2022-10-27 22:53 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        return true;
Esse return true não está fazendo nada porque em caso de erro vai simplesmente estourar uma exception

2022-10-27 22:54 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        return true;
Mesma coisa https://github.com/gregoryzimmerwarren/acceleration-everest-03-dotnet/pull/8#discussion_r1007443236

2022-10-27 22:54 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        return true;
Mesma coisa https://github.com/gregoryzimmerwarren/acceleration-everest-03-dotnet/pull/8#discussion_r1007443236

2022-10-27 22:56 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        if (portfolios.Count == 0)
```suggestion
        if (!portfolios.Any())
```

2022-10-27 22:57 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +            throw new ArgumentNullException($"No portfolio found for Id: {portfolioId}");
```suggestion
        var portfolio = await repository.SingleOrDefaultAsync(query).ConfigureAwait(false)
            ?? throw new ArgumentNullException($"No portfolio found for Id: {portfolioId}");
```

2022-10-28 11:54 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +            throw new ArgumentNullException($"No product found");
Eu coloco qual no lugar, o BadRequest() ou o Problem() ?

2022-10-28 12:08 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        return true;
Sim, inicialmente eu tinha pensado em usar como validador, mas depois vi que não era necessário e esqueci de tirar. Já alterei.

2022-10-28 12:08 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        return true;
Corrigido.

2022-10-28 12:08 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/PortfolioService.cs
> +        return true;
Corrigido.

2022-10-28 12:11 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/CustomerBankInfoController.cs
> +            var total = await _customerBankInfoAppService.GetTotalByCustomerIdAsync(customerId).ConfigureAwait(false);
Alterei para GetAccountBalanceByCustomerIdAsync

2022-10-28 12:12 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Services/CronJobExecuteOrders.cs
> +");
Muito obrigado pela info :)

2022-11-03 12:22 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +            throw new ArgumentNullException($"No product found");
Depois de conversar com o Lucas, eu coloquei um NoContent() em todos os meus GetAll.

2022-11-03 13:57 UTC, LucasPerinWarren approved these changes

2022-11-03 14:17 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/Api/Controllers/CustomerController.cs
> +    public async Task<IActionResult> GetByCustomerIdAsync(long customerId)
Estamos na controller de Customer, não há razão para colocar customer no url, apenas Id
```suggestion
    [HttpGet("{id}")]
    public async Task<IActionResult> GetByCustomerIdAsync(long Id)
```

2022-11-03 14:25 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/CustomerController.cs
> +    public async Task<IActionResult> GetByCustomerIdAsync(long customerId)
Alterado em todas as controllers

2022-11-03 14:26 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioController.cs
> +    [HttpPatch("invest/{customerId}")]
Por que customerId se não é esse o parâmetro passado?

2022-11-03 14:27 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioController.cs
> +    [HttpPatch("redeemToPortfolio/{customerId}")]
Igual anterior

2022-11-03 14:27 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioController.cs
> +    [HttpPatch("withdrawFromPortfolio/{customerId}")]
Igual

2022-11-03 14:34 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioController.cs
> +    [HttpPatch("invest/{customerId}")]
Corrigido

2022-11-03 14:34 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioController.cs
> +    [HttpPatch("redeemToPortfolio/{customerId}")]
Corrigido

2022-11-03 14:34 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/Api/Controllers/PortfolioController.cs
> +    [HttpPatch("withdrawFromPortfolio/{customerId}")]
Corrigido

2022-11-03 14:36 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppModels/Orders/OrderResultOtherDtos.cs
> +    }
```suggestion
        Product = product;
    }
```

2022-11-03 14:37 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppModels/Portfolios/CreatePortfolio.cs
> +    public long Id { get; set; }
Pra que serve esse Id?

2022-11-03 14:45 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Portfolios/CreatePortfolio.cs
> +    public long Id { get; set; }
Retirado

2022-11-03 15:46 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +
```suggestion
        createOrderDto.UnitPrice = await _productAppService.GetProductUnitPriceByIdAsync(createOrderDto.ProductId);
        createOrderDto.NetValue = createOrderDto.UnitPrice * createOrderDto.Quotes;
        createOrderDto.Direction = OrderDirection.Buy;

```

2022-11-03 15:46 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        createOrderDto.Direction = OrderDirection.Sell;
Igual o de cima

2022-11-03 15:50 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +
Feito

2022-11-03 15:50 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Services/PortfolioAppService.cs
> +        createOrderDto.Direction = OrderDirection.Sell;
Feito

2022-11-03 15:51 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Validators/Create/CreateProductValidator.cs
> +                .GreaterThanOrEqualTo(DateTime.Now.Date);
Acho que pode excluir essa validação.
```suggestion
```

2022-11-03 15:53 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/AppServices/Validators/Update/UpdateProductValidator.cs
> +                .GreaterThanOrEqualTo(DateTime.Now.Date);
Acho que pode tirar
```suggestion
```

2022-11-03 16:04 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +        var repository = _unitOfWork.Repository<CustomerBankInfo>();
Como é um get, deve-se usar o RepositoryFactory

2022-11-03 16:09 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerService.cs
> +        return query;
Essa variável não é uma query, mas um bool. Necessário trocar o nome da variável

2022-11-03 16:12 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/DomainService/Services/OrderService.cs
> +        return totalQuotes;
```suggestion
        var availableQuotes = 0;

        foreach (var order in orders)
        {
            if (order.Direction == OrderDirection.Buy)
            {
                availableQuotes += order.Quotes;
            }
            else
            {
                availableQuotes -= order.Quotes;
            }
        }

        return availableQuotes ;
```

2022-11-03 16:27 UTC, LeonardoAlthoff commented on acceleration-everest-03-dotnet/HostedServiceCronos/Properties/launchSettings.json
> +  "profiles": {
Excluir esse arquivo

2022-11-03 16:51 UTC, LeonardoAlthoff reviewed
Revisar comentários

2022-11-03 16:52 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/HostedServiceCronos/Properties/launchSettings.json
> +  "profiles": {
Este arquivo é o responsável pelas configurações de execução do HostedService.

2022-11-03 17:31 UTC, viniciusoliveira-warren approved these changes

2022-11-03 17:34 UTC, merged