EV 661 [.NET] 08 - Testes unitários
gregoryzimmerwarren/acceleration-everest-03-dotnet pull request #9
Opened 2022-11-03 17:42 UTC by gregoryzimmerwarren

**Objetivo**
_Nesta tarefa deverá ser implementado testes unitários para os seguintes projetos da sua aplicação:_

- 100% da Camada de aplicação;

- 100% da Camada de Domain.Services;

- Entidades de domínio caso possua regra de negócio embutida;

- Camada de Infraestrutura.

- O que não precisa ser testado?

- Camada de Application.Models;
 
- Camada de Api.

_Critérios de aceitação_
- Cobertura de testes acima de 70%.

![4](https://user-images.githubusercontent.com/113135420/201677454-8ec1db2c-3c3d-4c62-8ffd-f505c325fc2a.PNG)
![5](https://user-images.githubusercontent.com/113135420/201677460-7dddf280-eff0-40b9-a780-67201b34248d.PNG)
![6](https://user-images.githubusercontent.com/113135420/201677461-c9d4ddd7-973e-445c-893a-267abceebb79.PNG)

2022-11-04 16:43 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/AppServices/Validators/Create/CreateProductValidator.cs
>          private bool EnunIsValid(int direction)
```suggestion
        private bool EnumIsValid(int direction)
```

2022-11-04 16:50 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        });
Configuração do AutoMapper pode ser feita via injeção de dependência

2022-11-04 16:53 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        result.Should().NotBe(null);
```suggestion
        result.Should().NotBeNull();
```

2022-11-04 16:58 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppServices/Validators/Create/CreateProductValidator.cs
>          private bool EnunIsValid(int direction)
Alterado

2022-11-04 17:01 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        result.Should().NotBe(null);
Não há a opção direta de NotBeNull(), por isso optei pelo NotBe(null)

2022-11-04 18:28 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        result.Should().NotBe(null);
Perdão, não tinha visto que o retorno era um long, no caso então como número não pode ser nulo, o certo é ser 0. Ficaria assim:
`result.Should().NotBe(0);`

2022-11-04 18:29 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        result.Should().NotBe(null);
Tranquilo. E obrigado, já vou alterar.

2022-11-04 18:31 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        result.Should().NotBe(null);
Eu tinha cometido o mesmo erro em todos os métodos de Create, mas já alterei todos.

2022-11-04 19:10 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        await _customerAppService.DeleteAsync(idTest).ConfigureAwait(false);
```suggestion
        await _customerAppService.DeleteAsync(It.IsAny<long>()).ConfigureAwait(false);
```
Use e abuse dessa ferramenta quando o campo não é tão relevante

2022-11-07 11:48 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        await _customerAppService.DeleteAsync(idTest).ConfigureAwait(false);
Mesmo na Action? Achei que ali precisava ser utilizado um dado do Arrange.

2022-11-10 11:59 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppModels/Properties/launchSettings.json
> +}
Por que tem launch settings na app models?
```suggestion

```

2022-11-10 12:01 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppServices/Properties/launchSettings.json
> +}
Mesma situação do comentário sobre a AppModels.
```suggestion

```

2022-11-10 12:01 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/AppServices/Services/CustomerAppService.cs
```suggestion
    }

```

2022-11-10 12:03 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainModels/Models/CustomerBankInfo.cs
```suggestion
namespace DomainModels.Models;

```

2022-11-10 12:03 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Properties/launchSettings.json
> +}
Retirado. Bem como dos outros projetos.

2022-11-10 12:04 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerService.cs
>          var query = repository.SingleResultQuery().AndFilter(customer => customer.Id == id)
Por que UnitOfWork em um get?
```suggestion
        var repository = _repositoryFactory.Repository<Customer>();
        var query = repository.SingleResultQuery().AndFilter(customer => customer.Id == id)
```

2022-11-10 12:06 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/DomainServices.Tests/DomainServices.Tests.csproj
> +
Seus testes deveriam conhecer a API, mesmo caso da AppServices, passa ambos para um único projeto de testes que tenha referencia na API.

2022-11-10 12:21 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerService.cs
>          var query = repository.SingleResultQuery().AndFilter(customer => customer.Id == id)
Achei que precisava para fazer o teste funcionar, mas depois da ajuda do Claudinei percebi que era um erro meu mesmo.
Já passei para Repository Factory.

2022-11-10 12:22 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/ProductAppServiceTests.cs
> +
Acredito que seja interessante fazer testes mais assertivos, você pode verificar realmente se o seu GetProductUnitPriceByIdAsync, esta retornando o UnitPrice da entidade, recomendo adicionar a fixture de product no seu arrange, fazer o retorno do seu decimal UnitPrice e após isso comparar o seu result com o fixture.UnitPrice.

Recomendo verificar todas essas possibilidades nos outros testes, seus testes podem abusar de parâmentros genéricos, (It.IsAny()...) e mesmo assim, verificarem algo concreto.
```suggestion
    public void Should_GetProductUnitPriceByIdAsync_Successfully()
    {
        // Arrange
        var testProduct = Fixture.Create();
        var productId = testProduct.Id;
        var unitPrice = testProduct.UnitPrice;
        
        _mockProductService.Setup(productService => productService.GetProductUnitPriceByIdAsync(productId)).ReturnsAsync(unitPrice);

        // Action
        var result = _productAppService.GetProductUnitPriceByIdAsync(productId).ConfigureAwait(false);

        // Assert
        result.Should().Be(unitPrice);
        _mockProductService.Verify(productService => productService.GetProductUnitPriceByIdAsync(It.IsAny<long>()), Times.Once);
    }

```

2022-11-10 12:25 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/UnitTests/DomainServices/CustomerBankInfoServiceTests.cs
> +
```suggestion
        var customerBankInfoTest = CustomerBankInfoFixture.GenerateCustomerBankInfoFixture();

        _mockRepositoryFactory.Setup(repositoryFactory => repositoryFactory.Repository<CustomerBankInfo>()
        .SingleResultQuery().AndFilter(It.IsAny<Expression<Func<CustomerBankInfo, bool>>>())
        .Include(It.IsAny<Func<IQueryable<CustomerBankInfo>, IIncludableQueryable<CustomerBankInfo, object>>>())).Returns(It.IsAny<IQuery<CustomerBankInfo>>());
        
        _mockRepositoryFactory.Setup(repositoryFactory => repositoryFactory.Repository<CustomerBankInfo>()
        .SingleOrDefaultAsync(It.IsAny<IQuery<CustomerBankInfo>>(), default)).ReturnsAsync(customerBankInfoTest);
        
        _mockUnitOfWork.Setup(unitOfWork => unitOfWork.Repository<CustomerBankInfo>().Remove(customerBankInfoTest));

```

2022-11-10 12:31 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainServices.Tests/DomainServices.Tests.csproj
> +
Corrigi isso, porque eu havia mudado o projeto, mas por alguma razão essa parte ainda estava ai.

2022-11-10 12:47 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/UnitTests/Validators/Create/CreateCustomerValidatorTests.cs
> +    }
Acredito que para testes dos validators, como você tem Validations para cada prop, utilizar o TestValidate ao invés do Validate pois assim, podemos testar se o erro está vindo exatamente onde queremos.
```suggestion
    public void Should_NotCreateCustomer_When_FullName_Empty()
    {
        // Arrange
        var createCustomerTest = CreateCustomerFixture.GenerateCreateCustomerFixture();
        createCustomerTest.FullName = "";
        var validCreateCustomer = new CreateCustomerValidator();

        // Action
        var result = validCreateCustomer.TestValidate(createCustomerTest);

        // Assert
        result.ShouldHaveValidationErrorFor(x => x.FullName);
    }
```

2022-11-10 12:47 UTC, LucasPerinWarren commented on acceleration-everest-03-dotnet/UnitTests/Validators/Create/CreateCustomerValidatorTests.cs
> +
Como você esta utilizando em vários testes, fazer no ctor.

2022-11-10 12:49 UTC, LucasPerinWarren requested changes
Verificar comentários.

2022-11-10 14:36 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/DomainServices/CustomerBankInfoServiceTests.cs
> +
Corrigido em todos os arquivos de teste.

2022-11-10 15:12 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/Validators/Create/CreateCustomerValidatorTests.cs
> +    }
Alterado em todos os testes de validator.

2022-11-10 15:26 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/Validators/Create/CreateCustomerValidatorTests.cs
> +
Corrigido em todos os testes.

2022-11-11 14:36 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/ProductAppServiceTests.cs
> +
Alterado em todos os testes.

2022-11-11 19:04 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/AppModels/Orders/OrderResultForOtherDtos.cs
> +public class OrderResultForOtherDtos
```suggestion
public class OrderResult
```
Nomes devem ser autoexplicativos, mas quando autoexplicativos demais pode atrapalhar na interpretação.

2022-11-11 19:09 UTC, AlanmWarren commented on acceleration-everest-03-dotnet/AppModels/Orders/OrderResultForOtherDtos.cs
> +public class OrderResultForOtherDtos
Por que outra OrderResult?

2022-11-11 19:50 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerService.cs
> +            throw new ArgumentException("No customer found");
Não estamos fazendo nenhum filtro, se não encontrou nada é porque não tem dados o que significa que podemos remover essa exceção

2022-11-11 19:51 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +            throw new ArgumentException("No bank information found");
Mesma coisa https://github.com/gregoryzimmerwarren/acceleration-everest-03-dotnet/pull/9#discussion_r1020520273

2022-11-11 19:51 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/OrderService.cs
> +            throw new ArgumentException("No order found");
Mesma coisa https://github.com/gregoryzimmerwarren/acceleration-everest-03-dotnet/pull/9#discussion_r1020520273

2022-11-11 19:51 UTC, viniciusoliveira-warren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +            throw new ArgumentException("No product found");
Mesma coisa https://github.com/gregoryzimmerwarren/acceleration-everest-03-dotnet/pull/9#discussion_r1020520273

2022-11-11 20:18 UTC, viniciusoliveira-warren approved these changes
Tem arquivos que não possui testes tanto na camada de Aplication quanto Domain mas vou deixar aprovado. Assim que resolver isso pode mergear e seguir pro Canaveral (não precisa pedir review novamente)

2022-11-11 20:46 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/UnitTests/AppServices/CustomerAppServiceTests.cs
> +        });
Alterado

2022-11-11 20:49 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/AppModels/Orders/OrderResultForOtherDtos.cs
> +public class OrderResultForOtherDtos
Conversamos pelo slack, mas para deixar registrado aqui, eu tenho esses results diferentes porque por exemplo meu OrderResult tem informação do Portfolio, e no PortfolioResult tem da Order. Dai pra não criar um ciclo infinito porque um estaria puxando o outro, criei esses "ForOtherDtos", que não trazem essas informações.

2022-11-11 20:58 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerService.cs
> +            throw new ArgumentException("No customer found");
Removido.

2022-11-11 20:59 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/CustomerBankInfoService.cs
> +            throw new ArgumentException("No bank information found");
Removido.

2022-11-11 20:59 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/OrderService.cs
> +            throw new ArgumentException("No order found");
Removido.

2022-11-11 21:01 UTC, gregoryzimmerwarren commented on acceleration-everest-03-dotnet/DomainService/Services/ProductService.cs
> +            throw new ArgumentException("No product found");
Removido.

2022-11-14 13:55 UTC, merged